name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: build
        shell: bash
        run: |
          if [ "${{ matrix.os }}" != "windows-latest" ]; then
            export CFLAGS="-Wall -Wextra -Werror"
          fi
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j
